# -*- coding: utf-8 -*-
"""CS246-4d.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CVcG_3PDMLhD9lQoc1WfAncKYDRpHt2j

Must needed setup before every assignment
"""

!pip install pyspark
!pip install -U -q PyDrive
!apt install openjdk-8-jdk-headless -qq
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"

"""Imports"""

import itertools
import numpy as np

"""Code Variables"""

dataPath = 'user-shows.txt'
showsPath = 'shows.txt'
m = 9985
n = 563
alexi = 499 # user alexy ID
shows = []

"""Output"""

with open(showsPath) as f:
    for line in f:
        shows.append(line.strip())


R = np.zeros((m, n), dtype=np.int16)
with open(dataPath) as f:
    for i, line in enumerate(f):
        R[i, :] = list(map(int, line.split()))

p = np.sum(R, axis=1)
q = np.sum(R, axis=0)

p_ = 1 / np.sqrt(p)
q_ = 1 / np.sqrt(q)

RTp_ = R.T * p_[None, :]
Rq_ = R * q_[None, :]

rU = RTp_.T @ RTp_ @ R
rI = R @ Rq_.T @ Rq_

rU_focus = rU[alexi, :100]
rI_focus = rI[alexi, :100]

#only get top 5 results
rU_idx = np.argsort(rU_focus)[::-1][:5]
rI_idx = np.argsort(rI_focus)[::-1][:5]

rU_results = list(zip(rU_focus[rU_idx], rU_idx, [shows[i] for i in rU_idx]))
rI_results = list(zip(rI_focus[rI_idx], rI_idx, [shows[i] for i in rI_idx]))

print(rU_results)
print(rI_results)