# -*- coding: utf-8 -*-
"""CS246 2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHcKKl7Bn0_OeWccfT2tn98Z3f-qI34U

Imports
"""

import scipy.linalg as sl
import numpy as np

"""Ouptup"""

# https://stackoverflow.com/questions/21562986/numpy-matrix-vector-multiplication/21563036#21563036 for matrix multiplication
M = [[1, 2],
     [2, 1],
     [3, 4],
     [4, 3]]
M = np.array(M)
U, s, Vh = sl.svd(M, full_matrices=False)
print('U')
print(U)
print('Sigma')
print(s)
print('Vh')
print(Vh)

Evals, Evecs = sl.eigh(M.T @ M)

indices = np.argsort(Evals)

Evals = Evals[indices]
Evecs = Evecs[:, indices]

print('Evals')
print(Evals)
print('Evecs')
print(Evecs)